// ui constraints
export const SIDEBAR_TOGGLE = "SIDEBAR_TOGGLE";

// default constraints
export const LOADING_START = "LOADING_START";
export const CLOSE_ALERT_MS = "CLOSE_ALERT_MS";

// auth constraints
export const ISLOGGEDIN = "ISLOGGEDIN";
export const LOGOUT = "LOGOUT";
export const AUTHUSER = "AUTHUSER";
export const AUTH_FAILED = "AUTH_FAILED";

// register constraints
export const USER_REG_FAILED = "USER_REG_FAILED";
export const USER_REG_PASSED = "USER_REG_PASSED";

// events constraints
export const EVENTS_RETURNED = "EVENTS_RETURNED";

// events constraints
export const COURSES_RETURNED = "COURSES_RETURNED";
export const COURSE_RETURNED = "COURSE_RETURNED";
export const COURSE_UPDATE = "COURSE_UPDATE";
export const COURSE_DELETE = "COURSE_DELETE";
export const COURSE_SUCCESS = "COURSE_SUCCESS";
export const COURSE_FAILURE = "COURSE_FAILURE";
export const ARISE_COURSE_STATE = "ARISE_COURSE_STATE";
export const COURSE_STATUSES = "COURSE_STATUSES";
export const COURSES_BY_STATUS = "COURSES_BY_STATUS";
export const COURSE_BY_kEY = "COURSE_BY_kEY";
export const COURSES_REPORT = "COURSES_REPORT";

export const RETURN_USERS = "RETURN_USERS";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";

export const RETURN_ROLES = "RETURN_ROLES";
export const UPDATE_ROLE = "UPDATE_ROLE";
export const DELETE_ROLE = "DELETE_ROLE";
export const ROLE_REG_FAILED = "ROLE_REG_FAILED";
export const ROLE_REG_PASSED = "ROLE_REG_PASSED";

export const FACULTIES_RETURNED = "FACULTIES_RETURNED";
export const FACULTY_UPDATE = "FACULTY_UPDATE";
export const FACULTY_DELETE = "FACULTY_DELETE";
export const FACULTY_SUCCESS = "FACULTY_SUCCESS";
export const FACULTY_FAILURE = "FACULTY_FAILURE";

export const DEPARTMENTS_RETURNED = "DEPARTMENTS_RETURNED";
export const DEPARTMENT_UPDATE = "DEPARTMENT_UPDATE";
export const DEPARTMENT_DELETE = "DEPARTMENT_DELETE";
export const DEPARTMENT_SUCCESS = "DEPARTMENT_SUCCESS";
export const DEPARTMENT_FAILURE = "DEPARTMENT_FAILURE";

export const CHAPTER_SUCCESS = "CHAPTER_SUCCESS";
export const CHAPTER_DELETE = "CHAPTER_DELETE";
export const CHAPTER_UPDATE = "CHAPTER_UPDATE";
export const CHAPTER_FAILURE = "CHAPTER_FAILURE";
export const CHAPTER_RETURNED = "CHAPTER_RETURNED";

export const CLASSWORK_SUCCESS = "CLASSWORK_SUCCESS";
export const CLASSWORK_DELETE = "CLASSWORK_DELETE";
export const CLASSWORK_UPDATE = "CLASSWORK_UPDATE";
export const CLASSWORK_FAILURE = "CLASSWORK_FAILURE";
export const CLASSWORK_RETURNED = "CLASSWORK_RETURNED";

export const ATTENDANCE_SUCCESS = "ATTENDANCE_SUCCESS";
export const ATTENDANCE_FAILURE = "ATTENDANCE_FAILURE";
export const ATTENDANCE_RETURNED = "ATTENDANCE_RETURNED";

export const SESSION_SUCCESS = "SESSION_SUCCESS";
export const SESSION_DELETE = "SESSION_DELETE";
export const SESSION_UPDATE = "SESSION_UPDATE";
export const SESSION_FAILURE = "SESSION_FAILURE";
export const SESSION_RETURNED = "SESSION_RETURNED";

export const SEMESTER_RETRIEVE = "SEMESTER_RETRIEVE";
export const SEMESTER_REGISTRATION = "SEMESTER_REGISTRATION";
export const SEMESTER_UPDATE = "SEMESTER_UPDATE";
